### Ruta de prueba
GET http://localhost:3000/

### Listar mascotas
GET http://localhost:3000/mascotas

### Crear mascota
POST http://localhost:3000/mascotas
Content-Type: application/json

{
  "nombre": "Lucas",
  "especie": "Perro",
  "raza": "Caniche",
  "peso_kg": 5.7,
  "fecha_nacimiento": "2021-08-12"
}

### Eliminar mascota
DELETE http://localhost:3000/mascotas/1

### Listar horarios
GET http://localhost:3000/horarios

### Crear horario
POST http://localhost:3000/horarios
Content-Type: application/json

{
  "mascota_id": 1,
  "hora_local": "09:00:00",
  "gramos": 200,
  "dias": "1234567"
}

### Obtener Mascota por ID
GET http://localhost:3000/mascotas/1

### Actualizar Mascota
PUT http://localhost:3000/mascotas/1
Content-Type: application/json

{
  "nombre": "Calcu modificado",
  "especie": "Perro",
  "raza": "Labrador",
  "peso_kg": 18.0,
  "fecha_nacimiento": "2019-05-15"
}

### Horarios de una Mascota
GET http://localhost:3000/mascotas/1/horarios

### Actualizar Horario segun ID
PUT http://localhost:3000/horarios/1
Content-Type: application/json

{
  "hora_local": "18:30:00",
  "gramos": 220,
  "dias": "1234567",
  "activo": true
}

### Eliminar Horario
DELETE http://localhost:3000/horarios/1

### Listar usuarios
GET http://localhost:3000/usuarios

### Obtener usuario por ID
GET http://localhost:3000/usuarios/1

### Crear usuario
POST http://localhost:3000/usuarios
Content-Type: application/json

{
  "nombre": "britospark",
  "email": "lunaperritozahir@petcare.com",
  "password": "123456",
  "rol": "usuario"
}

### Actualizar usuario
PUT http://localhost:3000/usuarios/1
Content-Type: application/json

{
  "nombre": "Usuario Editado",
  "email": "demo@petcare.com",
  "rol": "admin"
}

### Eliminar usuario
DELETE http://localhost:3000/usuarios/1

### Login de usuario
POST http://localhost:3000/login
Content-Type: application/json

{
  "email": "demo@petcare.com",
  "password": "123456"
}
